- hosts: myweb
  vars_files:
   - var1.txt
  tasks:
  - package:
     name: "httpd"
     state: present
    register: x
  - package:
     name: "php"
  - copy:
     dest: "{{ doc_root }}/index.php" 
     src: "index.html"
  - service:
     name: "httpd"
     state: restarted
    when: x.rc == 0
  - firewalld:
     port: 80/tcp
     state: enabled
     permanent: yes
     immediate: yes


- hosts: mylb
  vars_files:
   - var1.txt
  tasks:
  - package:
     name: "haproxy"
     state: present
    register: z
  - package:
     name: "httpd"
     state: present
    register: x
  - template:
     dest: "/etc/haproxy/haproxy.cfg"
     src: "haproxy.cfg"
    when: z.rc == 0
  - service:
     name: "haproxy"
     state: restarted
    when: z.rc == 0 
  - service:
     name: "httpd"
     state: restarted
    when: x.rc == 0
  - firewalld:
     port: 80/tcp
     state: enabled
     permanent: yes
     immediate: yes

